name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    name: mvn verify (${{ matrix.profile }})

    strategy:
      matrix:
        profile: [default, legacy]

    steps:
      - uses: actions/checkout@v2

      - name: Cache ~/.m2/repository
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-${{ matrix.profile }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-${{ matrix.profile }}-maven-

      - if: ${{ matrix.profile == 'default' }}
        name: Set up jdk 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - if: ${{ matrix.profile == 'legacy' }}
        name: Set up jdk 8
        uses: actions/setup-java@v1
        with:
          java-version: 8

      - if: ${{ matrix.profile == 'default' }}
        name: mvn clean verify
        run: mvn -B clean verify

      - if: ${{ matrix.profile == 'legacy' }}
        name: mvn clean verify -Pjava-8,scala-2.11,spark-2.4
        run: mvn scala-cross-build:change-version -Pscala-2.11 && mvn -B clean verify -Pjava-8,scala-2.11,spark-2.4

# TODO: maven central? github packages? upload-artifact action?

# Github packages are not public :( https://github.community/t/download-from-github-package-registry-without-authentication/14407
#        run: mvn -B clean deploy
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
